export const mockedCharacters = [
  {
    id: 90,
    name: 'Daron Jefferson',
    image: 'https://rickandmortyapi.com/api/character/avatar/90.jpeg',
    species: 'Alien',
    key: 1090,
  },
  {
    id: 90,
    name: 'Daron Jefferson',
    image: 'https://rickandmortyapi.com/api/character/avatar/90.jpeg',
    species: 'Alien',
    key: -910,
  },
  {
    id: 150,
    name: 'Cornvelious Daniel',
    image: 'https://rickandmortyapi.com/api/character/avatar/150.jpeg',
    species: 'Alien',
    key: 1150,
  },
  {
    id: 150,
    name: 'Cornvelious Daniel',
    image: 'https://rickandmortyapi.com/api/character/avatar/150.jpeg',
    species: 'Alien',
    key: -850,
  },
  {
    id: 205,
    name: 'Little Dipper',
    image: 'https://rickandmortyapi.com/api/character/avatar/205.jpeg',
    species: 'Humanoid',
    key: 1205,
  },
  {
    id: 205,
    name: 'Little Dipper',
    image: 'https://rickandmortyapi.com/api/character/avatar/205.jpeg',
    species: 'Humanoid',
    key: -795,
  },
  {
    id: 397,
    name: 'Fido',
    image: 'https://rickandmortyapi.com/api/character/avatar/397.jpeg',
    species: 'Animal',
    key: 1397,
  },
  {
    id: 397,
    name: 'Fido',
    image: 'https://rickandmortyapi.com/api/character/avatar/397.jpeg',
    species: 'Animal',
    key: -603,
  },
  {
    id: 466,
    name: 'SEAL Team Rick',
    image: 'https://rickandmortyapi.com/api/character/avatar/466.jpeg',
    species: 'Human',
    key: 1466,
  },
  {
    id: 466,
    name: 'SEAL Team Rick',
    image: 'https://rickandmortyapi.com/api/character/avatar/466.jpeg',
    species: 'Human',
    key: -534,
  },
  {
    id: 798,
    name: 'Ferkusian',
    image: 'https://rickandmortyapi.com/api/character/avatar/798.jpeg',
    species: 'Alien',
    key: 1798,
  },
  {
    id: 798,
    name: 'Ferkusian',
    image: 'https://rickandmortyapi.com/api/character/avatar/798.jpeg',
    species: 'Alien',
    key: -202,
  },
]
